(function(){
  const canvas=document.querySelector("#scene"), panel=document.querySelector("#panel"), eyebrow=document.querySelector("#eyebrow"), title=document.querySelector("#title"), copy=document.querySelector("#copy"), button=document.querySelector("#next"), hint=document.querySelector("#hint"), progress=document.querySelector("#progress");
  const saved=(()=>{try{return JSON.parse(localStorage.getItem("poutyVerdict")||"null")}catch(e){return null}})();
  const data={date:saved? `${saved.departureDate.replace(" September "," Sept ")} — ${saved.returnDate}`:"24 Sept — 28 September 2026",mood:"Go Berserk",topics:(saved&&saved.subtopics&&saved.subtopics.length?saved.subtopics:["Shopping Spree","Street Food Hunt","Night Markets"]).join(" · ")};
  const steps=[
    {eyebrow:"Dossier opened",title:"The dates are<br><em>locked in.</em>",copy:`${data.date}. A very suspiciously perfect little long weekend.`,button:"Show me the next clue",hint:"The suitcase is ready. The story is just getting started."},
    {eyebrow:"Personality assessment: complete",title:"You chose to<br><em>go berserk.</em>",copy:`${data.topics}. A chaotic little love language, and frankly, excellent taste.`,button:"Okay, what else?",hint:"The suitcase has acquired several shopping bags. Naturally."},
    {eyebrow:"The stay you picked",title:"Room E has<br><em>made the cut.</em>",copy:"The whirlpool room. Bubbles, wine and a very convincing reason not to leave the hotel. 🛁",button:"Unlock the destination",hint:"A golden key has joined the evidence. One final secret remains."},
    {eyebrow:"Destination unlocked",title:"We’re going to<br><em>Bangkok.</em>",copy:"City lights, midnight street food, shopping bags and your hand in mine. The perfect recipe, isn’t it?",button:"Keep our secret safe",hint:"Your guy is officially cooking something special. 😎"}
  ];
  progress.innerHTML=steps.map(()=>"<i></i>").join(""); let step=-1;
  const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;
  const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x1b0c08,.055);const camera=new THREE.PerspectiveCamera(42,1,.1,100);camera.position.set(0,1.3,8);
  const root=new THREE.Group();scene.add(root); const gold=new THREE.MeshStandardMaterial({color:0xd8a75c,roughness:.32,metalness:.72}), leather=new THREE.MeshStandardMaterial({color:0x552619,roughness:.46,metalness:.14}), leatherDark=new THREE.MeshStandardMaterial({color:0x2a100b,roughness:.58,metalness:.1}), paper=new THREE.MeshStandardMaterial({color:0xe7cfaa,roughness:.7}), rose=new THREE.MeshStandardMaterial({color:0xc7655c,roughness:.4,metalness:.18});
  scene.add(new THREE.HemisphereLight(0xffd1a3,0x140806,2.2));const keyLight=new THREE.PointLight(0xffb466,38,18);keyLight.position.set(-3,4,5);scene.add(keyLight);const rim=new THREE.PointLight(0xd99a53,25,14);rim.position.set(4,1,-1);scene.add(rim);
  const floor=new THREE.Mesh(new THREE.CircleGeometry(7,64),new THREE.MeshStandardMaterial({color:0x1a0a07,roughness:.7,metalness:.1}));floor.rotation.x=-Math.PI/2;floor.position.y=-1.55;scene.add(floor);
  function box(w,h,d,mat,x,y,z,parent=root){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d,.12,.08,.12),mat);m.position.set(x,y,z);parent.add(m);return m}
  const suitcase=new THREE.Group();root.add(suitcase);const base=box(3,1.7,.72,leather,0,-.08,0,suitcase);const lid=box(3,1.53,.2,leather,-0.0,.02,.47,suitcase);lid.name="lid";box(3.12,.12,.12,gold,0,-.78,.48,suitcase);box(3.12,.1,.12,gold,0,.65,.48,suitcase);
  const handle=new THREE.Group();suitcase.add(handle);const tubeMat=gold;const left=new THREE.Mesh(new THREE.CylinderGeometry(.07,.07,.7,12),tubeMat), right=left.clone(),top=new THREE.Mesh(new THREE.CylinderGeometry(.07,.07,.85,12),tubeMat);left.rotation.z=Math.PI/2;right.rotation.z=Math.PI/2;top.rotation.z=Math.PI/2;left.position.set(-.7,1.05,0);right.position.set(.7,1.05,0);top.position.set(0,1.35,0);handle.add(left,right,top);handle.rotation.z=Math.PI/2;
  const tag=new THREE.Mesh(new THREE.BoxGeometry(.78,.48,.05),paper);tag.position.set(1.05,-.05,.58);tag.rotation.z=-.13;suitcase.add(tag);
  const bagGroup=new THREE.Group();bagGroup.visible=false;root.add(bagGroup);[[-1.6,-.75,.1,.75,.95,0xcd6d49],[1.55,-.85,.25,.68,.76,0x706c9a],[1.15,-.35,-.55,.5,.6,0x8a5636]].forEach(a=>{const b=box(a[3],a[4],.28,new THREE.MeshStandardMaterial({color:a[5],roughness:.55,metalness:.06}),a[0],a[1],a[2],bagGroup);const h=new THREE.Mesh(new THREE.TorusGeometry(a[3]*.22,.035,8,18),gold);h.position.set(a[0],a[1]+a[4]/2,a[2]);bagGroup.add(h)});
  const keyGroup=new THREE.Group();keyGroup.visible=false;root.add(keyGroup);const ring=new THREE.Mesh(new THREE.TorusGeometry(.32,.08,12,32),gold);ring.position.set(1.6,.45,.35);const shaft=new THREE.Mesh(new THREE.BoxGeometry(.16,1.25,.12),gold);shaft.position.set(1.6,-.3,.35);const tooth=box(.42,.18,.14,gold,1.76,-.72,.35,keyGroup);keyGroup.add(ring,shaft);
  const city=new THREE.Group();city.visible=false;root.add(city);for(let x=-3;x<=3;x+=.8){for(let z=-1.5;z<=1.5;z+=.8){const h=.3+Math.random()*1.55;const building=box(.48,h,.48,new THREE.MeshStandardMaterial({color:0x45211a,roughness:.55,metalness:.15,emissive:0x160804,emissiveIntensity:.3}),x,-1.35+h/2,z,city);if(Math.random()>.55){const light=box(.06,.07,.5,new THREE.MeshStandardMaterial({color:0xf4b45f,emissive:0xf4a53d,emissiveIntensity:1.3}),x,-1.35+h*.55,z+.245,city)}}} const moon=new THREE.Mesh(new THREE.SphereGeometry(.42,24,24),new THREE.MeshBasicMaterial({color:0xffd083}));moon.position.set(2.2,1.8,-1.8);city.add(moon);
  let targetRotation=.18,drag=false,lastX=0;canvas.addEventListener("pointerdown",e=>{drag=true;lastX=e.clientX});addEventListener("pointerup",()=>drag=false);addEventListener("pointermove",e=>{if(!drag)return;targetRotation+=(e.clientX-lastX)*.008;lastX=e.clientX});
  function resize(){const w=innerWidth,h=innerHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}addEventListener("resize",resize);resize();
  function selectStep(index){const s=steps[index];panel.classList.add("is-changing");setTimeout(()=>{eyebrow.textContent=s.eyebrow;title.innerHTML=s.title;copy.textContent=s.copy;button.innerHTML=`${s.button} <span aria-hidden="true">→</span>`;hint.textContent=s.hint;button.classList.toggle("dossier__button--final",index===steps.length-1);progress.querySelectorAll("i").forEach((dot,n)=>dot.classList.toggle("is-active",n<=index));panel.classList.remove("is-changing")},230);bagGroup.visible=index>=1;keyGroup.visible=index>=2;city.visible=index>=3;lid.rotation.x=index>=1?-.52:0;targetRotation=index===3?-.28:.18;keyLight.color.set(index===3?0xff8b3d:0xffb466)}
  button.addEventListener("click",()=>{if(step===steps.length-1){button.disabled=true;button.innerHTML="Secret secured <span aria-hidden=true>♥</span>";hint.textContent="Bangkok is waiting, Pouty. Now all you have to do is look cute and pack light.";return}step+=1;selectStep(step)});
  function animate(t){requestAnimationFrame(animate);root.rotation.y+=(targetRotation-root.rotation.y)*.035;root.rotation.x=Math.sin(t*.00055)*.045;root.position.y=Math.sin(t*.00085)*.07;suitcase.rotation.z=Math.sin(t*.00065)*.025;if(keyGroup.visible)keyGroup.rotation.y=t*.001;renderer.render(scene,camera)}animate(0);
})();